### ISSUE TITLE
Zielgruppe definieren

### ISSUE THREAD

**Issue by Theogra** [Nokcreate/Projektmodul-Prozesse#1]

**Comment by EggiEl** [comment]
siehe Figma Dokumentation. 

https://www.figma.com/file/Ugg6s2R6eKiEZ3gVlh6j0E/Gruppe-1?t=GS4g8xvAYYdri7KW-0

**Comment by arwinsf** [comment]
Mithilfe von [hier](https://www.figma.com/file/Ugg6s2R6eKiEZ3gVlh6j0E/Gruppe-1?node-id=1381-15&t=58b0jXUZwFXt9inW-4) erledigt, in welche Richtung wir gehen wollen und welche Zielgruppen wir bedienen wollen. Ergebnis -> Kranke, auf Pflege angewiesene
