### ISSUE TITLE
MVP_Ideation: Research 3D-Druck + Sensor Research

### ISSUE THREAD

**Issue by MartinLagleder** [Nokcreate/Projektmodul-Prozesse#17]
@EggiEl hier kannst du alle deine research ergebnisse vorläufig festhalten und dokumentieren.

**Comment by EggiEl** [comment]
Wurde von Gruppe abgesegnet.

**Comment by EggiEl** [comment]
Ergebnisse wurden in Figma geteilt, vorgestellt und besprochen.
