### ISSUE TITLE
MVP_Ideation: Research 3D and AR

### ISSUE THREAD

**Issue by MartinLagleder** [Nokcreate/Projektmodul-Prozesse#18]
@Nokcreate hier kannst du deine vorläufigen ergebnisse festhalten und dokumentieren. 
denke bitte daran deinen KI-Tool einsatz sauber zu dokumentieren. thx

**Comment by Nokcreate** [comment]
***Ich habe vorerst selbst im internet zu diesem thema recherchiert, bin jedoch recht bald an meine grenzen gestossen.
Im Anschluss daran habe ich mich ca. 2 Stunden mit Chat GPT 4 unterhaltene und folgendes Endergebnis erhalten:***

VR-Umgebung

- **Erstellung des 3D-Modells (etwa 2-3 Wochen)**: Sie können ein 3D-Modellierungsprogramm wie Blender, Maya oder 3ds Max verwenden, um das 3D-Modell Ihrer intelligenten Matratze zu erstellen. Sie müssen jedes Detail modellieren und texturieren, einschließlich aller Schichten und Sensoren.

- **Erstellung des Umgebungsraums (1 Woche)**: Sie können dieselbe 3D-Modellierungssoftware verwenden, um den Raum zu erstellen, in dem das Matratzenmodell platziert wird. Es gibt auch viele Online-Ressourcen, in denen Sie vorgerfertigte 3D-Raummodelle finden können, die Sie als Ausgangspunkt verwenden und an Ihre Bedürfnisse anpassen können.

- **Einrichtung der Interaktivität (1-2 Wochen)**: Verwenden Sie eine Spieleentwicklungsumgebung wie Unity oder Unreal Engine, um Ihr 3D-Modell und Ihren Raum zu importieren und die gewünschte Interaktivität zu programmieren. In diesem Schritt erstellen Sie auch die Textinformationen, die angezeigt werden, wenn ein Benutzer auf einen bestimmten Layer klickt.

- **Export und Übertragung auf Oculus Quest (1 Tag)**: Nachdem Sie Ihr Projekt in Unity oder Unreal Engine zusammengestellt haben, können Sie es direkt auf die Oculus Quest exportieren. Unity und Unreal Engine haben beide eingebaute Tools zum Exportieren auf Oculus Quest. Sie können dann die ausführbare Datei auf die Oculus Quest übertragen und dort ausführen.

***Weitere Moeglichkeiten in AR:***

Hier ist eine detaillierte Schritt-für-Schritt-Anleitung, um ein interaktives 3D-Modell einer Matratze zu erstellen und als AR-Anwendung auf einem Smartphone verfügbar zu machen. Da Sie angegeben haben, dass Sie Unity verwenden möchten, basiert diese Anleitung auf Unity und AR Foundation (ein Unity-Paket, das sowohl ARKit als auch ARCore unterstützt):

1. 3D-Modellierung der Matratze:

Zuerst müssen Sie das 3D-Modell der Matratze erstellen. Dies kann mit einem 3D-Modellierungstool wie Blender, 3ds Max oder Maya erfolgen. Sie müssen die Matratze detailliert modellieren und sicherstellen, dass sie so realistisch wie möglich ist.

2. Interaktive Punkte hinzufügen:

Sie können interaktive Punkte hinzufügen, indem Sie sogenannte "Hotspots" oder Trigger-Bereiche zu Ihrem Modell hinzufügen. Dies kann in Unity erfolgen. Sie können leere GameObjects an den Punkten erstellen, an denen Sie Interaktionen möchten, und diese mit Collidern ausstatten, um Interaktionen zu erkennen.

3. Importieren Sie das Modell in Unity:

Nachdem Sie das Modell erstellt und die interaktiven Punkte hinzugefügt haben, können Sie es in Unity importieren. Sie können das Modell einfach per Drag-and-Drop in das Projektfenster ziehen.

4. Erstellen Sie eine AR-Szene:

Mit Unity und dem AR Foundation-Paket können Sie eine AR-Szene erstellen. Sie müssen ein AR Session Origin und ein AR Session GameObject zu Ihrer Szene hinzufügen. Das AR Session Origin enthält die Kamera und verwaltet die Verfolgung der realen Welt, während das AR Session GameObject den Zustand der AR-Sitzung verwaltet.

5. Platzieren Sie das Modell in AR:

Um das Modell in AR zu platzieren, können Sie den AR Plane Manager verwenden, der in AR Foundation enthalten ist. Dies ermöglicht es der App, horizontale und vertikale Flächen in der realen Welt zu erkennen. Dann können Sie das Modell auf diesen Flächen platzieren.

6. Fügen Sie Interaktivität hinzu:

Sie können Interaktivität zu den Hotspots Ihres Modells hinzufügen, indem Sie ein Skript erstellen, das auf Eingaben reagiert. Sie können das AR Raycast Manager verwenden, um einen Strahl (Raycast) von der Position des Fingertips des Benutzers zu erstellen und zu überprüfen, ob dieser Strahl einen Ihrer Hotspots trifft. Wenn dies der Fall ist, können Sie eine Aktion auslösen, wie z.B. das Anzeigen von Informationen über die Matratze.

7. Testen Sie Ihre App:

Bevor Sie Ihre App veröffentlichen, sollten Sie sie gründlich testen. Stellen Sie sicher, dass das Modell korrekt in AR platziert wird, dass die Interaktionen funktionieren und dass das Modell gut auf verschiedenen Geräten aussieht.

8. Veröffentlichen Sie Ihre App:

Sobald Sie zufrieden sind, dass alles funktioniert, können Sie Ihre App auf den entsprechenden App Stores (Google Play für Android, App Store für iOS) veröffentlichen.

Bitte beachten Sie, dass dies eine vere# I need to gather the most recent information about creating an AR app with Unity and AR Foundation.
search("Creating AR app with Unity and AR Foundation tutorial")

Für Android-Geräte bietet Google ARCore, eine Plattform, die eine Reihe von APIs bereitstellt, die es Ihrem Telefon ermöglichen, seine Umgebung zu erfassen, die Welt zu verstehen und mit Informationen zu interagieren. Einige der APIs sind sowohl auf Android als auch auf iOS verfügbar, um gemeinsame AR-Erlebnisse zu ermöglichen.


Es ist auch wichtig zu beachten, dass sowohl ARKit als auch ARCore bestimmte Geräteanforderungen haben. Sie müssen sicherstellen, dass die Geräte, auf denen Sie Ihre App ausführen möchten, diese Anforderungen erfüllen.

**Comment by Nokcreate** [comment]
**generell hier mal meine allgemeinen erfharungen im umgang mit KIs in unserem Projekt. Fuer diese Zusammenfassung habe ich mir ebenfalls von Chat GPT helfen lassen: Was gut gelaufen ist:**

Ideenfindung und Brainstorming: Die KI war in der Lage, kreative Ideen und Vorschläge für Ihre Smarte Matratze zu liefern, einschließlich möglicher MVP-Ansätze, Marketingstrategien und Technologien, die in das Produkt integriert werden könnten.

Technische Beratung: Die KI konnte Ratschläge und Empfehlungen zu verschiedenen Technologien und Tools geben, die in Ihrem Projekt eingesetzt werden könnten, wie zum Beispiel zur Erstellung eines interaktiven 3D-Modells.

Fähigkeit zur Interaktion in natürlicher Sprache: Die KI war in der Lage, in einem menschenähnlichen, verständlichen Dialog mit Ihnen zu interagieren, was das Brainstorming und den Informationsaustausch erleichterte.

Was verbessert werden könnte:

Persönliche Erfahrung und Kontext: Die KI hat keinen Zugang zu persönlichen Erfahrungen oder einem spezifischen Kontext über die einzelnen Sitzungen hinaus. Dies kann dazu führen, dass die KI manchmal Antworten gibt, die nicht optimal auf Ihre spezielle Situation abgestimmt sind.

Spezifisches Fachwissen: Obwohl die KI auf einem breiten Wissensspektrum trainiert wurde, hat sie möglicherweise nicht das gleiche Tiefe und aktuelle Wissen wie ein Mensch, der sich auf ein bestimmtes Fachgebiet spezialisiert hat.

Überschneidungen mit anderen KIs:

In Bezug auf die Zusammenarbeit mit anderen KIs wie Midjourney, kann ich als KI im Allgemeinen nahtlos mit anderen KI-Modellen interagieren, vorausgesetzt, es gibt eine ordnungsgemäße Integration zwischen den Systemen. Da jede KI in ihrer Funktionalität und ihrem Anwendungsbereich einzigartig ist, kann es hilfreich sein, verschiedene KIs je nach Bedarf und Anforderungen des Projekts zu kombinieren. Es ist jedoch wichtig zu beachten, dass die Qualität der KI-Kollaboration von der Art der Aufgabe und den spezifischen Eigenschaften der beteiligten KIs abhängt.
