### ISSUE TITLE
MVP_Ideation: Research 3D embedding in website/app

### ISSUE THREAD

**Issue by MartinLagleder** [Nokcreate/Projektmodul-Prozesse#19]
@arwinsf hier kannst du deine voräufigen ergebnisse deines researches festhalten und dokumentieren. 
vergiss nicht den einsatz von KI-tools sauber zu dokumentieren.

**Comment by arwinsf** [comment]
Als Basis habe ich mir ein gut bekanntes Web Framework wie Vite mit VueJS vorgestellt. Damit habe ich auch Entwicklungserfahrung.

Die ersten großen und beliebten Packages, die man in das Projekt einbinden kann, sind:

1. Wahl [TreeJS](https://tresjs.org/), <a href="https://github.com/tresjs/tres" target="_blank">GitHub</a>
2. Wahl [ThreeJS](https://threejs.org/), <a href="https://github.com/mrdoob/three.js/" target="_blank">GitHub</a>

Eine dieser Packages (die erste bevorzugt) wird installiert und dann das vorhandene Modell eingebunden. Wie vorher besprochen eignet sich zunächst mal ein Platzhaltermodell, um die Funktionalität testen zu können.

Guides, in denen konkret gezeigt wird, wie genau das Einbetten funktioniert, findet man hier:
https://tresjs.org/examples/load-models.html
https://www.youtube.com/watch?v=ZM7EeS75sYM
https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html

**Comment by arwinsf** [comment]
Recherche geprüft und abgeschlossen, Inhalt auf Figma gepostet
