### ISSUE TITLE
Produktideen sammeln

### ISSUE THREAD

**Issue by Theogra** [Nokcreate/Projektmodul-Prozesse#2]

**Comment by EggiEl** [comment]
Ideen waren nach dem letzten Gruppentreffen:

Brille für Hör-Geschädigte, Smart-Brille, Smart- Blindenstock...

**Comment by MartinLagleder** [comment]
# Augmented-Reality-Brille mit generativer KI für eine neuartige Interaktion mit der Umgebung und Geräten im Haushalt

Beschreibung: Eine Augmented-Reality-Brille mit generativer KI könnte Menschen mit eingeschränkter Mobilität oder Behinderungen eine neue Möglichkeit bieten, ihre Umgebung und Geräte im Haushalt zu steuern und wahrzunehmen. Die Brille nutzt Sensoren und Kameras, um die Umgebung zu erfassen und mithilfe von generativer KI zu interpretieren. Virtuelle Buttons, Schalter oder andere interaktive Elemente werden dann in das Sichtfeld des Nutzers eingeblendet, die er per Augenbewegungen oder Gesten steuern kann.

Durch die Verbindung von virtuellen Elementen mit der physischen Umgebung ermöglicht die Augmented-Reality-Brille mit generativer KI eine neuartige Art der Interaktion mit der Umwelt und den Geräten im Haushalt. Dies könnte beispielsweise durch das Anschauen eines Lichtschalters, das Ein- oder Ausschalten des Lichts im Raum ermöglicht werden oder durch eine bestimmte Handbewegung das Fenster geöffnet oder geschlossen werden.

**Comment by MartinLagleder** [comment]
# Idee für "Haus Sinnvoll"

Ich habe mich außerdem mit der Leitung eines Heims für schwerbehinderte Kinder in Verbindung gesetzt.
Eine Idee/Wunsch wäre ein KI-Assistent, welcher für jeden Patienten eine individuelle Logistik/Dokumentation über die benötigten Medikamente führt. Inklusive frühzeitiger Nachbestellung bei geringen Reseven und Reminder für die Pfleger.
In wieweit eine generative KI in diesem Produkt vorkommt müsste man morgen beim Gruppenmeeting besprechen. 

Im Rahmen der Prep Research soll das nur als kleiner Anreiz dienen.

**Comment by MartinLagleder** [comment]
# Inklusives Konzerterlebnis für Taube durch generative KI

Unser Produkt ("SoundSense"?) ermöglicht tauben Menschen ein barrierefreies Konzerterlebnis. Durch die Nutzung von generativer KI werden Audiosignale in Echtzeit in haptische und visuelle Reize übersetzt. So können Nutzer sich frei und unabhängig im Konzert bewegen und die Atmosphäre in vollen Zügen genießen. SoundSense wird kostenlos an der Konzertkasse verliehen, um Inklusion und Teilhabe für alle zu ermöglichen.

**Comment by MartinLagleder** [comment]
Das "SoundSense"- Produkt könnte man mit einer art Weste, Handschuhe, Schuhe, Armbänder, ... verwirklichen. 
Aus Design-Sicht könnte man sich da enorm gut austoben.

**Comment by EggiEl** [comment]
Eine Intelligente Dekubitus Matratze, 

Matratze überwacht Bettlägerige Pflegepatienten und analysiert Lageposition und Belastung. Lagert Patientinnen Intelligent via Luftkompression um. 
Entlastet Pflegepersonal, die sonst alle paar Stunden eine Umlagerung vornehmen müssen. Hilft bei der Pflegedokumentation und dem Lagerungsplan und kann bei ärztlicher Visite eine Hilfestellung sein um schmerzen bei Patienten zu lokalisieren, welche diese nicht mehr selbst benennen können. (Patient belastet Körperteil nicht mehr, weil schmerzen, KI erkennt das und Dokumentiert) 



Matratze kann zusätzlich Feuchtegrad messen zur Infektions-Verhinderrung. 
Ersetzt die Klingelmatte. Patienten die gefährdet sind aus dem Bett zu fallen, oder Demente, die unbeaufsichtigt das Bett verlassen und sich gefährden, werden von der Matratzen KI beaufsichtigt und das Pflegeperson benachrichtigt, falls einer der Fälle eintrifft.

**Comment by EggiEl** [comment]
Hatte Rücksprache mit Kumpel aus Pflegebereich, der die Idee Sinnvoll fand.

**Comment by EggiEl** [comment]
# Idee für "Haus Sinnvoll"
Ich habe mich außerdem mit der Leitung eines Heims für schwerbehinderte Kinder in Verbindung gesetzt.
Eine Idee/Wunsch wäre ein KI-Assistent, welcher für jeden Patienten eine individuelle Logistik/Dokumentation über die benötigten Medikamente führt. Inklusive frühzeitiger Nachbestellung bei geringen Reseven und Reminder für die Pfleger.
In wieweit eine generative KI in diesem Produkt vorkommt müsste man morgen beim Gruppenmeeting besprechen.


Im Rahmen der Prep Research soll das nur als kleiner Anreiz dienen.

Originally posted by @MartinLagleder in https://github.com/Nokcreate/Projektmodul-Prozesse/issues/2#issuecomment-1485734918

Durchaus sinnvoll, aber aus eigener Erfahrung ist es schwierig mit Medikamenten zu planen, weil die immer von der ärztlichen Visite abhängt und ohne den zuständigen Arzt keine Medikamente vergeben, bestellt oder angeordnet werden dürfen.

**Comment by EggiEl** [comment]
> Eine Intelligente Dekubitus Matratze,
> 
> Matratze überwacht Bettlägerige Pflegepatienten und analysiert Lageposition und Belastung. Lagert Patientinnen Intelligent via Luftkompression um. Entlastet Pflegepersonal, die sonst alle paar Stunden eine Umlagerung vornehmen müssen. Hilft bei der Pflegedokumentation und dem Lagerungsplan und kann bei ärztlicher Visite eine Hilfestellung sein um schmerzen bei Patienten zu lokalisieren, welche diese nicht mehr selbst benennen können. (Patient belastet Körperteil nicht mehr, weil schmerzen, KI erkennt das und Dokumentiert)
> 
> Matratze kann zusätzlich Feuchtegrad messen zur Infektions-Verhinderrung. Ersetzt die Klingelmatte. Patienten die gefährdet sind aus dem Bett zu fallen, oder Demente, die unbeaufsichtigt das Bett verlassen und sich gefährden, werden von der Matratzen KI beaufsichtigt und das Pflegeperson benachrichtigt, falls einer der Fälle eintrifft.

Ah und die Idee vom Pflege Kumpel war: Wenn Patient nachts aufsteht um auf die Toilette zu gehen, macht die KI das Licht an. Gibt oft stürze wegen sowas. Und das fällt erst beim nächsten Rundgang auf.

**Comment by Nokcreate** [comment]
Da sind doch schon mal ein paar Ideen zusammengekommen. Warten wir mal ab was die Konkurrenz heut so raus haut

**Comment by Xixxxi** [comment]
In den Bereichen Smart-Brille und Hörgeräte, habe ich als Orientierung die bereits vorhanden Konkurrenzprodukte rausgesucht und auf figma zusammengefasst.

**Comment by Xixxxi** [comment]
Zudem hier noch ein paar Ideen meinerseits (werden auch aufs figma board notiert): 

1. Ein intelligenter Rollstuhl, der sich durch Gedankensteuerung bewegen lässt: Dies könnte Menschen mit körperlichen Einschränkungen, die Schwierigkeiten haben, ihre Muskeln zu kontrollieren, helfen, sich selbstständiger zu bewegen.

2. Ein intelligenter Arm-Prothesen-Roboter: Für Menschen, die einen Arm oder eine Hand verloren haben, könnte ein Roboter mit KI-Technologie entwickelt werden, der Bewegungen und Handlungen durch Gedankensteuerung erfasst und ausführt.

3. Ein intelligenter Rollator, der Hindernisse erkennt und ausweicht: Ältere Menschen oder Menschen mit Mobilitätseinschränkungen können Schwierigkeiten haben, Hindernisse wie unebene Oberflächen oder Stufen zu erkennen und zu umgehen. Ein intelligenter Rollator könnte helfen, indem er Hindernisse automatisch erkennt und ausweicht.

**Comment by arwinsf** [comment]
Gesammelt [hier](https://www.figma.com/file/Ugg6s2R6eKiEZ3gVlh6j0E/Gruppe-1?node-id=111-729&t=58b0jXUZwFXt9inW-4). Entschieden für Smart Matratze
