### ISSUE TITLE
GitHub aufräumen

### ISSUE THREAD

**Issue by MartinLagleder** [Nokcreate/Projektmodul-Prozesse#20]
@arwinsf du hattest mal gesagt du räumst das Repository auf.... würdest du dem bitte noch nachkommen ?
also eine gescheite Home seite hochziehen mit unserer Landing Page von der austellung, Logo, und aktuellen status quo ?
ich bin mir auch sicher, dass theo dir dabei gut helfen kann :)

Wenn du das grundgerüst gebaut hast kann ich anschließenden den aktuellen scrum einbauen. 
aber erledig du bitte alles bis zum stand letzter woche. 
Danke

**Comment by arwinsf** [comment]
https://github.com/Nokcreate/Projektmodul-Prozesse/tree/main
