### ISSUE TITLE
Use-Case Diagram : Patient

### ISSUE THREAD

**Issue by MartinLagleder** [Nokcreate/Projektmodul-Prozesse#21]
erstelle bitte ein Ue-Case diagramm für alle use-cases aus sichtweise des Patienten

**Comment by EggiEl** [comment]
Wurde erstellt und in Figma mit Reflektion und Fragen für nächstes Treffen hochgeladen. Gerne anschauen und Rückmeldung geben :) und dann Issue schließen.

**Comment by EggiEl** [comment]
![image](https://github.com/Nokcreate/Projektmodul-Prozesse/assets/116878106/a07ca6aa-3f92-4d2b-ba02-72069d18e1b1)

**Comment by EggiEl** [comment]
Wurde vorgestellt und von Gruppenmitgliedern abgesegnet.
