### ISSUE TITLE
Ergänzung des Product Backlogs

### ISSUE THREAD

**Issue by MartinLagleder** [Nokcreate/Projektmodul-Prozesse#24]
ergänze bitte das Product backlog soweit wie möglich
ich habe dir ein template auf figma gebastelt mit einer notiz für dich.
achte bitte darauf dass du die formatierung nicht zerschießt wenn du neue Post-Its hinzufügst.

**Comment by Theogra** [comment]
Ich habe einige Ergänzungen zum Produkt-Backlog vorgenommen, werde das Issue jedoch nicht schließen, da im Laufe des Projekts weitere hinzugefügt werden

**Comment by Theogra** [comment]
habe dieses Issue auf Scrum 2 umgestellt :)
