### ISSUE TITLE
(Team-) Research für VR/AR MVP

### ISSUE THREAD

**Issue by Theogra** [Nokcreate/Projektmodul-Prozesse#25]
Hallo @MartinLagleder @Xixxxi @Nokcreate , hier könnt ihr eure Forschung zur Machbarkeit des VR/AR-MVP wie besprochen veröffentlichen und diskutieren, ob es in 4 Wochen implementiert werden kann

Hier noch einmal die personenspezifischen Aufgaben für diesen Rechercheteil:

Martin, Du übernimmst die Recherche für die Umsetzung in Blender
Gianni, du recherchierst für den Unity-Klick-Dummy
Koni, du übernimmst die Recherche zur Realisierung der Umsetzung für VR/AR-Brillen

**Comment by Nokcreate** [comment]
habe den wuerfel von martin bekommen. es hat zwar eine zeit gedauert, aber ich habe es geschafft diesen auf der oculus verfuegbar zu machen, so dass man diesen ueber vr in einer eigenen umgebung anschauen kann. von der seite aus kann ich also sagen dass man die idee umsetzen kann.

**Comment by Nokcreate** [comment]
Die Umsetzung ist nach jetzigem stand der dinge kein problem, wir koennen externe apps auf der oculus launchen oder auch direkt die testumgebung von unity benutzen um eine bessere performance in der demo zu erhalten. das setting steht soweit, wie auch die ersten on klick events unserer matratze.
