### ISSUE TITLE
(Team -) Research für physischen MVP

### ISSUE THREAD

**Issue by Theogra** [Nokcreate/Projektmodul-Prozesse#26]
Hallo @arwinsf @EggiEl, wie bereits erwähnt, recherchiert ihr nach der Machbarkeit des physischen MVP. Hier könnt ihr eure Ergebnisse teilen und diskutieren, ob der MVP in 4 Wochen umgesetzt werden kann.

Personenbezogene Aufgabenverteilung:

Elias, du baust einen ersten (Vor-)Prototyp und prüfst die Umsetzung mit dem Raspberry Pi.
Arwin, du bist für die weitere Online-Recherche zur Umsetzung des physischen Prototyps verantwortlich

**Comment by arwinsf** [comment]
Ich habe auf Figma relevante Sensoren / Sensorgruppen, die man für eine Dekubitusmatratze erwägen kann, aufgelistet mit Links.
