### ISSUE TITLE
Prep Research

### ISSUE THREAD

**Issue by Nokcreate** [Nokcreate/Projektmodul-Prozesse#4]
https://www.thisisservicedesigndoing.com/methods/preparatory-research

erstmal lesen und einfach Gedanken machen.

**Comment by EggiEl** [comment]
habe ich gelsen und angefangen an paar unserer Ideen zu recherchieren. 

Blindenstock ist ne bekannte Idee leider mit patent: 
https://www.radio7.de/zuhause/news/der-intelligente-blindenstock-aus-aalen
https://www.vdk.de/nord/pages/83963/kieler_studenten_entwickeln_intelligenten_blindenstock

**Comment by MartinLagleder** [comment]
sehr schön, aber bitte lasst uns alle Ideen auch in dem dafür vorgesehenen Issue sammeln und diskutieren.
Hier ist noch der Link zum Issue: https://github.com/Nokcreate/Projektmodul-Prozesse/issues/2

**Comment by MartinLagleder** [comment]
Im Rahmen der Prep Research habe ich mit mit dem "Haus Sinnvoll" in Verbindung gesetzt.
Was ist das?: 
-> In der Intensivkinder-WG "Haus SinnVoll" in Pocking umsorgen, pflegen und fördern wir schwerstkranke, beatmete und intensivpflegebedürftige Kinder und Jugendliche rund um die Uhr - und das in einer familiären Umgebung.

Gebt mir mal Bescheid wenn ihr dafür seid in diese Richtung weiter zu recherchieren.

**Comment by EggiEl** [comment]
Ich hab in figma dazu auch eine Dokumentspalte angelegt. Da bitte auch eintragen

**Comment by Xixxxi** [comment]
Auch hier hinterlasse ich euch meine Geistesblitze (wird wieder in figma festgehalten):

Fokus: Sehbehinderte

1. Ein Braille-Drucker für den Heimgebrauch: Ein Braille-Drucker für den Heimgebrauch würde es blinden Menschen ermöglichen, schnell und einfach Braille-Dokumente auszudrucken, ohne auf teure und zeitaufwendige externe Dienstleistungen angewiesen zu sein.

2. Eine elektronische Braille-Uhr: Eine elektronische Braille-Uhr würde blinden Menschen die Möglichkeit geben, die Zeit schnell und einfach abzulesen, ohne auf akustische Signale oder andere Hilfsmittel angewiesen zu sein.

3. Eine App zur Beschreibung von Bildern: Eine App, die Bilder beschreiben kann, könnte blinden Menschen helfen, visuelle Informationen besser zu verstehen. Die App würde automatisch eine Beschreibung des Bildes vorlesen und Details wie Farben, Formen und Gegenstände identifizieren.

**Comment by arwinsf** [comment]
Erledigt [hier](https://www.figma.com/file/Ugg6s2R6eKiEZ3gVlh6j0E/Gruppe-1?node-id=107-460&t=SsQVHyPJjZFIVxjv-4)
