### ISSUE TITLE
How to Issue

### ISSUE THREAD

**Issue by EggiEl** [Nokcreate/Projektmodul-Prozesse#5]
Bitte denkt dran. Die issues sollten bis zum Ende eines Milestones alle mal kommentiert, gereviewed und im besten Fall geclosed werden. 
Im Laufe des Projekts wird es Einzelaufgaben geben, die bitte von mindestens einem Gruppenmitglied vor dem closen nochmal kontrolliert werden sollten. 

Allen viel Spaß beim Issue Krieg :D. Lasset die Spiele beginnen.

**Comment by Xixxxi** [comment]
Hier nochmal ein Tutorial zum Thema: 

- Wie verfasst man GitHub Issues?

Link: https://docs.github.com/en/issues/tracking-your-work-with-issues/quickstart
