### ISSUE TITLE
THE YEAR 2033: RESEARCH TASK / SELF-ETHNOGRAPHIC RESEARCH

### ISSUE THREAD

**Issue by MartinLagleder** [Nokcreate/Projektmodul-Prozesse#7]
Sammelt bis zum Termin nächste Woche Eindrücke aus eurem Themenbereich, indem ihr eure Alltagserfahrungen in diesem Bereich dokumentiert (z.B. Fotodokumentation mit dem Smartphone) und euch einen möglichen KI-Einfluss dazu vorstellt.

Versucht dabei auch zu bedenken, wie sich eure Zukunftsvision und eure Produktidee (solltet ihr bereits erste Ideen dazu haben) auf die dokumentierten Abläufe auswirken könnten. Dokumentiert hier eure Ergebnisse und diskutiert sie in der folgenden Woche gemeinsam.

genauere Infos findet ihr auf Figma....

**Comment by arwinsf** [comment]
Erledigt [hier](https://www.figma.com/file/Ugg6s2R6eKiEZ3gVlh6j0E/Gruppe-1?node-id=172-14&t=0E4sHtLvHBlFc2Iv-4)
