### ISSUE TITLE
THE YEAR 2033: RESEARCH TASK / CONTEXTUAL INTERVIEW

### ISSUE THREAD

**Issue by MartinLagleder** [Nokcreate/Projektmodul-Prozesse#8]
Die Produkt/Service-Idee die ihr entwickelt, wird nicht nur euch selbst betreffen. Ihr müsst also auch verstehen, wie sich andere Akteuere in euren ausgewählten Bereichen verhalten und welche Prozesse, Bedürfnisse und Anforderungen für sie eine Rolle spielen. Es ist also Zeit, euch andere Perspektiven einzuholen, und zwar über das CONTEXTUAL INTERVIEW.  

Geht dazu folgendermaßen vor: Besprecht gemeinsam, welche Akteure für euren Themenbereich eine Rolle spielen und führt mit Individuen aus diesen Gruppen kurze Interviews. Für den Bereich Mobilität können das z.B. Pendler oder Touristen sein oder im Bereich Kultur Museumsbesucher:innen oder auch Kurator:innen, etc. 

  **WICHTIG:** Solltet ihr euch dazu entschieden haben, das Thema gesellschaftliche Teilhabe & Inklusion zu eurem Themenbereich dazu zu nehmen, sprecht unbedingt mit Leuten aus den benachteiligten oder marginalisierten Gruppen, die Teil eurer Überlegungen sind - ohne ihre Perspektive und Wünsche und Bedürfnisse zu kennen, könnt ihr kein Konzept für sie entwickeln.  Dokumentiert sowohl eure Interviewfragen, als auch eure Ergebnisse hier.

alle weiteren Infos wie immer auf Figma...

**Comment by arwinsf** [comment]
Frame [hier](https://www.figma.com/file/Ugg6s2R6eKiEZ3gVlh6j0E/Gruppe-1?node-id=1020-26&t=0E4sHtLvHBlFc2Iv-4), erstes Interview von Elias erledigt. Eins von mir folgt noch

**Comment by arwinsf** [comment]
@Xixxxi und @Theogra sollen ihr Interview dann auch eintragen im Frame

**Comment by arwinsf** [comment]
Meins wurde eingetragen, wie steht es mit @Xixxxi ?

**Comment by Xixxxi** [comment]
Ist drin
