### ISSUE TITLE
Development Mapping

### ISSUE THREAD

**Issue by MartinLagleder** [Nokcreate/Projektmodul-Prozesse#9]
Überlegt euch  gemeinsam auf dem Frame wie sich generative KI in eurem Bereich im Laufe der nächsten 10 Jahre auswirken könnte.  Wenn es euch hilft, könnt ihr dabei in 2 Jahres-Schritten denken. Ihr könnt aber auch einfach wild 10 Jahre in die Zukunft spekulieren. Nutzt dabei auch gerne Bildmaterial oder was immer euch beim Spekulieren hilft.

**Comment by MartinLagleder** [comment]
# Hier ist der Stand vom Dienstag, 28.03.2023

![Development Mapping](https://user-images.githubusercontent.com/66225084/228316273-11ecae72-e10d-4ead-9b1f-699124feadb2.jpg)

**Comment by MartinLagleder** [comment]
Schauts euch bitte alle die Fimga File nochmal an und wenn niemand mehr was zu ergänzen weis dann bitte dieses Issue schließen.

**Comment by arwinsf** [comment]
Erledigt [hier](https://www.figma.com/file/Ugg6s2R6eKiEZ3gVlh6j0E/Gruppe-1?node-id=111-693&t=0E4sHtLvHBlFc2Iv-4)
